require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReferralsController do

  # This should return the minimal set of attributes required to create a valid
  # Referral. As you add validations to Referral, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "code" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReferralsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all referrals as @referrals" do
      referral = Referral.create! valid_attributes
      get :index, {}, valid_session
      assigns(:referrals).should eq([referral])
    end
  end

  describe "GET show" do
    it "assigns the requested referral as @referral" do
      referral = Referral.create! valid_attributes
      get :show, {:id => referral.to_param}, valid_session
      assigns(:referral).should eq(referral)
    end
  end

  describe "GET new" do
    it "assigns a new referral as @referral" do
      get :new, {}, valid_session
      assigns(:referral).should be_a_new(Referral)
    end
  end

  describe "GET edit" do
    it "assigns the requested referral as @referral" do
      referral = Referral.create! valid_attributes
      get :edit, {:id => referral.to_param}, valid_session
      assigns(:referral).should eq(referral)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Referral" do
        expect {
          post :create, {:referral => valid_attributes}, valid_session
        }.to change(Referral, :count).by(1)
      end

      it "assigns a newly created referral as @referral" do
        post :create, {:referral => valid_attributes}, valid_session
        assigns(:referral).should be_a(Referral)
        assigns(:referral).should be_persisted
      end

      it "redirects to the created referral" do
        post :create, {:referral => valid_attributes}, valid_session
        response.should redirect_to(Referral.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved referral as @referral" do
        # Trigger the behavior that occurs when invalid params are submitted
        Referral.any_instance.stub(:save).and_return(false)
        post :create, {:referral => { "code" => "invalid value" }}, valid_session
        assigns(:referral).should be_a_new(Referral)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Referral.any_instance.stub(:save).and_return(false)
        post :create, {:referral => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested referral" do
        referral = Referral.create! valid_attributes
        # Assuming there are no other referrals in the database, this
        # specifies that the Referral created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Referral.any_instance.should_receive(:update).with({ "code" => "MyString" })
        put :update, {:id => referral.to_param, :referral => { "code" => "MyString" }}, valid_session
      end

      it "assigns the requested referral as @referral" do
        referral = Referral.create! valid_attributes
        put :update, {:id => referral.to_param, :referral => valid_attributes}, valid_session
        assigns(:referral).should eq(referral)
      end

      it "redirects to the referral" do
        referral = Referral.create! valid_attributes
        put :update, {:id => referral.to_param, :referral => valid_attributes}, valid_session
        response.should redirect_to(referral)
      end
    end

    describe "with invalid params" do
      it "assigns the referral as @referral" do
        referral = Referral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Referral.any_instance.stub(:save).and_return(false)
        put :update, {:id => referral.to_param, :referral => { "code" => "invalid value" }}, valid_session
        assigns(:referral).should eq(referral)
      end

      it "re-renders the 'edit' template" do
        referral = Referral.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Referral.any_instance.stub(:save).and_return(false)
        put :update, {:id => referral.to_param, :referral => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested referral" do
      referral = Referral.create! valid_attributes
      expect {
        delete :destroy, {:id => referral.to_param}, valid_session
      }.to change(Referral, :count).by(-1)
    end

    it "redirects to the referrals list" do
      referral = Referral.create! valid_attributes
      delete :destroy, {:id => referral.to_param}, valid_session
      response.should redirect_to(referrals_url)
    end
  end

end
